git:
  depth: 3

language: cpp

compiler:
  - gcc
  - clang

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required

    - os: osx
      osx_image: xcode7.3
      sudo: required


before_install:
  - sudo sh ./scripts/install_gtest.sh

script:
  - make
  - make run

