git:
  depth: 3

language: cpp

compiler:
  - gcc-4.8
  - clang-3.6

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required

    - os: osx
      osx_image: xcode7.3
      sudo: required


before_install:
  - sudo apt-get -qq update
  - sudo sh ./scripts/install_gtest.sh

script:
  - make
  - make run

